-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local CS_ENUM_PB = require("cs_enum_pb")


local localTable = {}
ACCELERATEWARNNOTIFY = protobuf.Descriptor()
localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD = protobuf.FieldDescriptor()


localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD.name = "AcceCount"
localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD.full_name = "cs.AccelerateWarnNotify.AcceCount"
localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD.number = 1
localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD.index = 0
localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD.label = 1
localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD.has_default_value = false
localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD.default_value = 0
localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD.type = 13
localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD.cpp_type = 3

ACCELERATEWARNNOTIFY.name = "AccelerateWarnNotify"
ACCELERATEWARNNOTIFY.full_name = "cs.AccelerateWarnNotify"
ACCELERATEWARNNOTIFY.nested_types = {}
ACCELERATEWARNNOTIFY.enum_types = {}
ACCELERATEWARNNOTIFY.fields = {localTable.ACCELERATEWARNNOTIFY_ACCECOUNT_FIELD}
ACCELERATEWARNNOTIFY.is_extendable = false
ACCELERATEWARNNOTIFY.extensions = {}

AccelerateWarnNotify = protobuf.Message(ACCELERATEWARNNOTIFY)

