-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"


local localTable = {}
PERSONALINFO = protobuf.Descriptor()
localTable.PERSONALINFO_EDUCATION_FIELD = protobuf.FieldDescriptor()
localTable.PERSONALINFO_POWER_FIELD = protobuf.FieldDescriptor()
localTable.PERSONALINFO_INTELLIGENCE_FIELD = protobuf.FieldDescriptor()
localTable.PERSONALINFO_AGILE_FIELD = protobuf.FieldDescriptor()


localTable.PERSONALINFO_EDUCATION_FIELD.name = "Education"
localTable.PERSONALINFO_EDUCATION_FIELD.full_name = "cs.PersonalInfo.Education"
localTable.PERSONALINFO_EDUCATION_FIELD.number = 1
localTable.PERSONALINFO_EDUCATION_FIELD.index = 0
localTable.PERSONALINFO_EDUCATION_FIELD.label = 1
localTable.PERSONALINFO_EDUCATION_FIELD.has_default_value = false
localTable.PERSONALINFO_EDUCATION_FIELD.default_value = ""
localTable.PERSONALINFO_EDUCATION_FIELD.type = 9
localTable.PERSONALINFO_EDUCATION_FIELD.cpp_type = 9

localTable.PERSONALINFO_POWER_FIELD.name = "Power"
localTable.PERSONALINFO_POWER_FIELD.full_name = "cs.PersonalInfo.Power"
localTable.PERSONALINFO_POWER_FIELD.number = 2
localTable.PERSONALINFO_POWER_FIELD.index = 1
localTable.PERSONALINFO_POWER_FIELD.label = 1
localTable.PERSONALINFO_POWER_FIELD.has_default_value = false
localTable.PERSONALINFO_POWER_FIELD.default_value = 0
localTable.PERSONALINFO_POWER_FIELD.type = 13
localTable.PERSONALINFO_POWER_FIELD.cpp_type = 3

localTable.PERSONALINFO_INTELLIGENCE_FIELD.name = "Intelligence"
localTable.PERSONALINFO_INTELLIGENCE_FIELD.full_name = "cs.PersonalInfo.Intelligence"
localTable.PERSONALINFO_INTELLIGENCE_FIELD.number = 3
localTable.PERSONALINFO_INTELLIGENCE_FIELD.index = 2
localTable.PERSONALINFO_INTELLIGENCE_FIELD.label = 1
localTable.PERSONALINFO_INTELLIGENCE_FIELD.has_default_value = false
localTable.PERSONALINFO_INTELLIGENCE_FIELD.default_value = 0
localTable.PERSONALINFO_INTELLIGENCE_FIELD.type = 13
localTable.PERSONALINFO_INTELLIGENCE_FIELD.cpp_type = 3

localTable.PERSONALINFO_AGILE_FIELD.name = "Agile"
localTable.PERSONALINFO_AGILE_FIELD.full_name = "cs.PersonalInfo.Agile"
localTable.PERSONALINFO_AGILE_FIELD.number = 4
localTable.PERSONALINFO_AGILE_FIELD.index = 3
localTable.PERSONALINFO_AGILE_FIELD.label = 1
localTable.PERSONALINFO_AGILE_FIELD.has_default_value = false
localTable.PERSONALINFO_AGILE_FIELD.default_value = 0
localTable.PERSONALINFO_AGILE_FIELD.type = 13
localTable.PERSONALINFO_AGILE_FIELD.cpp_type = 3

PERSONALINFO.name = "PersonalInfo"
PERSONALINFO.full_name = "cs.PersonalInfo"
PERSONALINFO.nested_types = {}
PERSONALINFO.enum_types = {}
PERSONALINFO.fields = {localTable.PERSONALINFO_EDUCATION_FIELD, localTable.PERSONALINFO_POWER_FIELD, localTable.PERSONALINFO_INTELLIGENCE_FIELD, localTable.PERSONALINFO_AGILE_FIELD}
PERSONALINFO.is_extendable = false
PERSONALINFO.extensions = {}

PersonalInfo = protobuf.Message(PERSONALINFO)

