// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/cs_personal.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cs {

  /// <summary>Holder for reflection information generated from protocol/cs_personal.proto</summary>
  public static partial class CsPersonalReflection {

    #region Descriptor
    /// <summary>File descriptor for protocol/cs_personal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CsPersonalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chpwcm90b2NvbC9jc19wZXJzb25hbC5wcm90bxICY3MiVQoMUGVyc29uYWxJ",
            "bmZvEhEKCUVkdWNhdGlvbhgBIAEoCRINCgVQb3dlchgCIAEoDRIUCgxJbnRl",
            "bGxpZ2VuY2UYAyABKA0SDQoFQWdpbGUYBCABKA1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cs.PersonalInfo), global::Cs.PersonalInfo.Parser, new[]{ "Education", "Power", "Intelligence", "Agile" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PersonalInfo : pb::IMessage<PersonalInfo>,IComponent {
    private static readonly pb::MessageParser<PersonalInfo> _parser = new pb::MessageParser<PersonalInfo>(() => new PersonalInfo());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PersonalInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cs.CsPersonalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonalInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonalInfo(PersonalInfo other) : this() {
      education_ = other.education_;
      power_ = other.power_;
      intelligence_ = other.intelligence_;
      agile_ = other.agile_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonalInfo Clone() {
      return new PersonalInfo(this);
    }

    /// <summary>Field number for the "Education" field.</summary>
    public const int EducationFieldNumber = 1;
    private string education_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Education {
      get { return education_; }
      set {
        education_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Power" field.</summary>
    public const int PowerFieldNumber = 2;
    private uint power_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Power {
      get { return power_; }
      set {
        power_ = value;
      }
    }

    /// <summary>Field number for the "Intelligence" field.</summary>
    public const int IntelligenceFieldNumber = 3;
    private uint intelligence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Intelligence {
      get { return intelligence_; }
      set {
        intelligence_ = value;
      }
    }

    /// <summary>Field number for the "Agile" field.</summary>
    public const int AgileFieldNumber = 4;
    private uint agile_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Agile {
      get { return agile_; }
      set {
        agile_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PersonalInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PersonalInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Education != other.Education) return false;
      if (Power != other.Power) return false;
      if (Intelligence != other.Intelligence) return false;
      if (Agile != other.Agile) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Education.Length != 0) hash ^= Education.GetHashCode();
      if (Power != 0) hash ^= Power.GetHashCode();
      if (Intelligence != 0) hash ^= Intelligence.GetHashCode();
      if (Agile != 0) hash ^= Agile.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Education.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Education);
      }
      if (Power != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Power);
      }
      if (Intelligence != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Intelligence);
      }
      if (Agile != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Agile);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Education.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Education);
      }
      if (Power != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Power);
      }
      if (Intelligence != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Intelligence);
      }
      if (Agile != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Agile);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PersonalInfo other) {
      if (other == null) {
        return;
      }
      if (other.Education.Length != 0) {
        Education = other.Education;
      }
      if (other.Power != 0) {
        Power = other.Power;
      }
      if (other.Intelligence != 0) {
        Intelligence = other.Intelligence;
      }
      if (other.Agile != 0) {
        Agile = other.Agile;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Education = input.ReadString();
            break;
          }
          case 16: {
            Power = input.ReadUInt32();
            break;
          }
          case 24: {
            Intelligence = input.ReadUInt32();
            break;
          }
          case 32: {
            Agile = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
