//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class ModuleBaseEntity {

    public ViewSystemCompoent viewSystemCompoent { get { return (ViewSystemCompoent)GetComponent(ModuleBaseComponentsLookup.ViewSystemCompoent); } }
    public bool hasViewSystemCompoent { get { return HasComponent(ModuleBaseComponentsLookup.ViewSystemCompoent); } }

    public ViewSystemCompoent AddViewSystemCompoent() {
        var component = CreateComponent<ViewSystemCompoent>(ModuleBaseComponentsLookup.ViewSystemCompoent);
        AddComponent(ModuleBaseComponentsLookup.ViewSystemCompoent, component);
        return component;
    }

    public void ReplaceViewSystemCompoent(ViewSystemCompoent compoent) {
        var component = CreateComponent<ViewSystemCompoent>(ModuleBaseComponentsLookup.ViewSystemCompoent);
        ReplaceComponent(ModuleBaseComponentsLookup.ViewSystemCompoent, component);
    }

    public void RemoveViewSystemCompoent() {
        RemoveComponent(ModuleBaseComponentsLookup.ViewSystemCompoent);
    }
}
