//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentContextGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

public partial class ModuleBaseContext {

    public ModuleBaseEntity uIManagerCompoentEntity { get { return GetGroup(ModuleBaseMatcher.UIManagerCompoent).GetSingleEntity(); } }
    public UIManagerCompoent uIManagerCompoent { get { return uIManagerCompoentEntity.uIManagerCompoent; } }
    public bool hasUIManagerCompoent { get { return uIManagerCompoentEntity != null; } }

    public ModuleBaseEntity SetUIManagerCompoent() {
        if(hasUIManagerCompoent) {
            throw new EntitasException("Could not set uIManagerCompoent!\n" + this + " already has an entity with UIManagerCompoentComponent!",
                "You should check if the context already has a uIManagerCompoentEntity before setting it or use context.ReplaceUIManagerCompoent().");
        }
        var entity = CreateEntity();
        entity.AddUIManagerCompoent();
        return entity;
    }

    public void ReplaceUIManagerCompoent(UIManagerCompoent compoent) {
        var entity = uIManagerCompoentEntity;
        if(entity == null) {
            entity = SetUIManagerCompoent();
        } else {
            entity.ReplaceUIManagerCompoent(compoent);
        }
    }

    public void RemoveUIManagerCompoent() {
        DestroyEntity(uIManagerCompoentEntity);
    }
}
