//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class ModuleManagerEntity {

    public ModuleManagerCompoent moduleManagerCompoent { get { return (ModuleManagerCompoent)GetComponent(ModuleManagerComponentsLookup.ModuleManagerCompoent); } }
    public bool hasModuleManagerCompoent { get { return HasComponent(ModuleManagerComponentsLookup.ModuleManagerCompoent); } }

    public ModuleManagerCompoent AddModuleManagerCompoent() {
        var component = CreateComponent<ModuleManagerCompoent>(ModuleManagerComponentsLookup.ModuleManagerCompoent);
        AddComponent(ModuleManagerComponentsLookup.ModuleManagerCompoent, component);
        return component;
    }

    public void ReplaceModuleManagerCompoent(ModuleManagerCompoent compoent) {
        var component = CreateComponent<ModuleManagerCompoent>(ModuleManagerComponentsLookup.ModuleManagerCompoent);
        ReplaceComponent(ModuleManagerComponentsLookup.ModuleManagerCompoent, component);
    }

    public void RemoveModuleManagerCompoent() {
        RemoveComponent(ModuleManagerComponentsLookup.ModuleManagerCompoent);
    }
}
