//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestModuleEntity {

    public Cs.PersonalInfo personalInfo { get { return (Cs.PersonalInfo)GetComponent(TestModuleComponentsLookup.PersonalInfo); } }
    public bool hasPersonalInfo { get { return HasComponent(TestModuleComponentsLookup.PersonalInfo); } }

    public Cs.PersonalInfo AddPersonalInfo() {
        var component = CreateComponent<Cs.PersonalInfo>(TestModuleComponentsLookup.PersonalInfo);
        AddComponent(TestModuleComponentsLookup.PersonalInfo, component);
        return component;
    }

    public void ReplacePersonalInfo(Cs.PersonalInfo compoent) {
        var component = CreateComponent<Cs.PersonalInfo>(TestModuleComponentsLookup.PersonalInfo);
        ReplaceComponent(TestModuleComponentsLookup.PersonalInfo, component);
    }

    public void RemovePersonalInfo() {
        RemoveComponent(TestModuleComponentsLookup.PersonalInfo);
    }
}
