//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestModuleEntity {

    public TestViewObject testViewObject { get { return (TestViewObject)GetComponent(TestModuleComponentsLookup.TestViewObject); } }
    public bool hasTestViewObject { get { return HasComponent(TestModuleComponentsLookup.TestViewObject); } }

    public TestViewObject AddTestViewObject() {
        var component = CreateComponent<TestViewObject>(TestModuleComponentsLookup.TestViewObject);
        AddComponent(TestModuleComponentsLookup.TestViewObject, component);
        return component;
    }

    public void ReplaceTestViewObject(TestViewObject compoent) {
        var component = CreateComponent<TestViewObject>(TestModuleComponentsLookup.TestViewObject);
        ReplaceComponent(TestModuleComponentsLookup.TestViewObject, component);
    }

    public void RemoveTestViewObject() {
        RemoveComponent(TestModuleComponentsLookup.TestViewObject);
    }
}
