//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ContextGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

public sealed partial class TestModuleContext : Context<TestModuleEntity> {

    public TestModuleContext()
        : base(
            TestModuleComponentsLookup.TotalComponents,
            0,
            new ContextInfo(
                "TestModule",
                TestModuleComponentsLookup.componentNames,
                TestModuleComponentsLookup.componentTypes
            )
        ) {
    }
}