//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentsLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class TestModuleComponentsLookup {

    public const int HeroInfo = 0;
    public const int PersonalInfo = 1;
    public const int TestViewObject = 2;

    public const int TotalComponents = 3;

    public static readonly string[] componentNames = {
        "HeroInfo",
        "PersonalInfo",
        "TestViewObject"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(HeroInfo),
        typeof(Cs.PersonalInfo),
        typeof(TestViewObject)
    };
}
