//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.MatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

public sealed partial class TestModuleMatcher {

    static IMatcher<TestModuleEntity> _matcherPersonalInfo;

    public static IMatcher<TestModuleEntity> PersonalInfo {
        get {
            if(_matcherPersonalInfo == null) {
                var matcher = (Matcher<TestModuleEntity>)Matcher<TestModuleEntity>.AllOf(TestModuleComponentsLookup.PersonalInfo);
                matcher.componentNames = TestModuleComponentsLookup.componentNames;
                _matcherPersonalInfo = matcher;
            }

            return _matcherPersonalInfo;
        }
    }
}
