//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.MatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

public sealed partial class TestModuleMatcher {

    static IMatcher<TestModuleEntity> _matcherHeroInfo;

    public static IMatcher<TestModuleEntity> HeroInfo {
        get {
            if(_matcherHeroInfo == null) {
                var matcher = (Matcher<TestModuleEntity>)Matcher<TestModuleEntity>.AllOf(TestModuleComponentsLookup.HeroInfo);
                matcher.componentNames = TestModuleComponentsLookup.componentNames;
                _matcherHeroInfo = matcher;
            }

            return _matcherHeroInfo;
        }
    }
}
