//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.MatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

public sealed partial class TestModuleMatcher {

    static IMatcher<TestModuleEntity> _matcherTestViewObject;

    public static IMatcher<TestModuleEntity> TestViewObject {
        get {
            if(_matcherTestViewObject == null) {
                var matcher = (Matcher<TestModuleEntity>)Matcher<TestModuleEntity>.AllOf(TestModuleComponentsLookup.TestViewObject);
                matcher.componentNames = TestModuleComponentsLookup.componentNames;
                _matcherTestViewObject = matcher;
            }

            return _matcherTestViewObject;
        }
    }
}
