//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ContextGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

public sealed partial class ModuleManagerContext : Context<ModuleManagerEntity> {

    public ModuleManagerContext()
        : base(
            ModuleManagerComponentsLookup.TotalComponents,
            0,
            new ContextInfo(
                "ModuleManager",
                ModuleManagerComponentsLookup.componentNames,
                ModuleManagerComponentsLookup.componentTypes
            )
        ) {
    }
}
