//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentsLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class ModuleManagerComponentsLookup {

    public const int ModuleManagerCompoent = 0;

    public const int TotalComponents = 1;

    public static readonly string[] componentNames = {
        "ModuleManagerCompoent"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(ModuleManagerCompoent)
    };
}
