//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.MatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

public sealed partial class ModuleBaseMatcher {

    static IMatcher<ModuleBaseEntity> _matcherViewSystemCompoent;

    public static IMatcher<ModuleBaseEntity> ViewSystemCompoent {
        get {
            if(_matcherViewSystemCompoent == null) {
                var matcher = (Matcher<ModuleBaseEntity>)Matcher<ModuleBaseEntity>.AllOf(ModuleBaseComponentsLookup.ViewSystemCompoent);
                matcher.componentNames = ModuleBaseComponentsLookup.componentNames;
                _matcherViewSystemCompoent = matcher;
            }

            return _matcherViewSystemCompoent;
        }
    }
}
