//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.MatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

public sealed partial class ModuleBaseMatcher {

    static IMatcher<ModuleBaseEntity> _matcherUIManagerCompoent;

    public static IMatcher<ModuleBaseEntity> UIManagerCompoent {
        get {
            if(_matcherUIManagerCompoent == null) {
                var matcher = (Matcher<ModuleBaseEntity>)Matcher<ModuleBaseEntity>.AllOf(ModuleBaseComponentsLookup.UIManagerCompoent);
                matcher.componentNames = ModuleBaseComponentsLookup.componentNames;
                _matcherUIManagerCompoent = matcher;
            }

            return _matcherUIManagerCompoent;
        }
    }
}
