//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentsLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class ModuleBaseComponentsLookup {

    public const int UIManagerCompoent = 0;
    public const int ViewSystemCompoent = 1;

    public const int TotalComponents = 2;

    public static readonly string[] componentNames = {
        "UIManagerCompoent",
        "ViewSystemCompoent"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(UIManagerCompoent),
        typeof(ViewSystemCompoent)
    };
}
