//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ContextGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

public sealed partial class ModuleBaseContext : Context<ModuleBaseEntity> {

    public ModuleBaseContext()
        : base(
            ModuleBaseComponentsLookup.TotalComponents,
            0,
            new ContextInfo(
                "ModuleBase",
                ModuleBaseComponentsLookup.componentNames,
                ModuleBaseComponentsLookup.componentTypes
            )
        ) {
    }
}
