-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"


local localTable = {}
LEVELCONFIG = protobuf.Descriptor()
localTable.LEVELCONFIG_ID_FIELD = protobuf.FieldDescriptor()
localTable.LEVELCONFIG_NAME_FIELD = protobuf.FieldDescriptor()
localTable.LEVELCONFIG_LEVELRESID_FIELD = protobuf.FieldDescriptor()
LEVELCONFIGARRAY = protobuf.Descriptor()
localTable.LEVELCONFIGARRAY_ITEMS_FIELD = protobuf.FieldDescriptor()


localTable.LEVELCONFIG_ID_FIELD.name = "ID"
localTable.LEVELCONFIG_ID_FIELD.full_name = "dataconfig.LevelConfig.ID"
localTable.LEVELCONFIG_ID_FIELD.number = 1
localTable.LEVELCONFIG_ID_FIELD.index = 0
localTable.LEVELCONFIG_ID_FIELD.label = 1
localTable.LEVELCONFIG_ID_FIELD.has_default_value = false
localTable.LEVELCONFIG_ID_FIELD.default_value = 0
localTable.LEVELCONFIG_ID_FIELD.type = 13
localTable.LEVELCONFIG_ID_FIELD.cpp_type = 3

localTable.LEVELCONFIG_NAME_FIELD.name = "Name"
localTable.LEVELCONFIG_NAME_FIELD.full_name = "dataconfig.LevelConfig.Name"
localTable.LEVELCONFIG_NAME_FIELD.number = 2
localTable.LEVELCONFIG_NAME_FIELD.index = 1
localTable.LEVELCONFIG_NAME_FIELD.label = 1
localTable.LEVELCONFIG_NAME_FIELD.has_default_value = false
localTable.LEVELCONFIG_NAME_FIELD.default_value = ""
localTable.LEVELCONFIG_NAME_FIELD.type = 9
localTable.LEVELCONFIG_NAME_FIELD.cpp_type = 9

localTable.LEVELCONFIG_LEVELRESID_FIELD.name = "LevelResID"
localTable.LEVELCONFIG_LEVELRESID_FIELD.full_name = "dataconfig.LevelConfig.LevelResID"
localTable.LEVELCONFIG_LEVELRESID_FIELD.number = 3
localTable.LEVELCONFIG_LEVELRESID_FIELD.index = 2
localTable.LEVELCONFIG_LEVELRESID_FIELD.label = 1
localTable.LEVELCONFIG_LEVELRESID_FIELD.has_default_value = false
localTable.LEVELCONFIG_LEVELRESID_FIELD.default_value = 0
localTable.LEVELCONFIG_LEVELRESID_FIELD.type = 13
localTable.LEVELCONFIG_LEVELRESID_FIELD.cpp_type = 3

LEVELCONFIG.name = "LevelConfig"
LEVELCONFIG.full_name = "dataconfig.LevelConfig"
LEVELCONFIG.nested_types = {}
LEVELCONFIG.enum_types = {}
LEVELCONFIG.fields = {localTable.LEVELCONFIG_ID_FIELD, localTable.LEVELCONFIG_NAME_FIELD, localTable.LEVELCONFIG_LEVELRESID_FIELD}
LEVELCONFIG.is_extendable = false
LEVELCONFIG.extensions = {}
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.name = "items"
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.full_name = "dataconfig.LevelConfigArray.items"
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.number = 1
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.index = 0
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.label = 3
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.has_default_value = false
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.default_value = {}
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.message_type = LEVELCONFIG
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.type = 11
localTable.LEVELCONFIGARRAY_ITEMS_FIELD.cpp_type = 10

LEVELCONFIGARRAY.name = "LevelConfigArray"
LEVELCONFIGARRAY.full_name = "dataconfig.LevelConfigArray"
LEVELCONFIGARRAY.nested_types = {}
LEVELCONFIGARRAY.enum_types = {}
LEVELCONFIGARRAY.fields = {localTable.LEVELCONFIGARRAY_ITEMS_FIELD}
LEVELCONFIGARRAY.is_extendable = false
LEVELCONFIGARRAY.extensions = {}

LevelConfig = protobuf.Message(LEVELCONFIG)
LevelConfigArray = protobuf.Message(LEVELCONFIGARRAY)

