//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ProtobufDataConfigSystemsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ProtobufDataConfigSystems), typeof(Entitas.Feature));
		L.RegFunction("Uninstall", Uninstall);
		L.RegFunction("ReadDataConfigForLua", ReadDataConfigForLua);
		L.RegFunction("UninstallForLua", UninstallForLua);
		L.RegFunction("New", _CreateProtobufDataConfigSystems);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateProtobufDataConfigSystems(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ProtobufDataConfigSystems obj = new ProtobufDataConfigSystems();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ProtobufDataConfigSystems.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Uninstall(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			ProtobufDataConfigSystems.Uninstall(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReadDataConfigForLua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			LuaInterface.LuaByteBuffer o = ProtobufDataConfigSystems.ReadDataConfigForLua(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UninstallForLua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			ProtobufDataConfigSystems.UninstallForLua(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

