//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TcpNetworkSystemsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TcpNetworkSystems), typeof(Entitas.Feature));
		L.RegFunction("New", _CreateTcpNetworkSystems);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTcpNetworkSystems(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				TcpNetworkSystems obj = new TcpNetworkSystems();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: TcpNetworkSystems.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

